config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/about' => 'home#about', :as => 'about'
  get '/help' => 'home#help', :as => 'help'
  get '/privacy' => 'home#privacy', :as => 'privacy'
  
  devise_for :users, :path => 'u',:controllers => { :sessions => "sessions", :omniauth_callbacks => "omniauth_callbacks" }
  
  resources :users do
    member do
      put 'enable'
      put 'disable'
      put 'disable_and_reset'
      put 'force_confirm'
    end
    collection do
      get 'stats'
    end
    resource :user_account
    resources :roles
  end
  
  get '/maps/activity' => 'audits#for_map_model', :as => "maps_activity"
  
  resources :maps  do
    member do
      post 'map_type'
      get 'export'
      get 'warp'
      get 'clip'
      post 'rectify'
      get 'align'
      get 'warped'
      get 'metadata'
      get 'comments'
      get 'delete'
      get 'status'
      get 'publish'
      get 'unpublish'
      post 'save_mask_and_warp'
      delete 'delete_mask'
      post 'warp_aligned'
      get 'gcps'
      get 'rough_state' => 'maps#get_rough_state'
      post 'rough_state' => 'maps#set_rough_state'
      get 'rough_centroid'=> 'maps#get_rough_centroid'
      post 'rough_centroid' => 'maps#set_rough_centroid'
      get 'id'
      get 'trace'
      get 'idland'
    end
    collection do
        get 'geosearch'
        get 'tag'
        get 'csv'
    end
    resources :layers
  end
  
  get '/maps/tag/:query' => 'maps#tag', :as => "map_tag"
  
  get '/mapimages/:id.gml.ol' => 'maps#get_mask', :as => "masking_map"
  get '/maps/thumb/:id' => 'maps#thumb', :as =>'thumb_map'
  get '/maps/thumb' => 'maps#thumb', :as => 'map_thumb_base'
  get '/layers/thumb' => 'layers#thumb', :as => 'layer_thumb_base'
  get '/mosaics/thumb/:id' => 'layers#thumb', :as =>'thumb_layer'
  get '/layers/thumb/:id' => 'layers#thumb'
 
  
  get '/gcps/bulk_import' => 'gcps#bulk_import', :as => "bulk_import_gcps"
  get '/gcps/csv' => 'gcps#csv', :as =>'csv_gcps'
  get '/gcps/:id' => 'gcps#show', :as => "gcp"
  delete '/gcps/:id/destroy' => 'gcps#destroy', :as => "destroy_gcp"
  post '/gcps/add/:mapid' => 'gcps#add', :as => "add_gcp"
  put '/gcps/update/:id' => 'gcps#update', :as => "update_gcp"
  put '/gcps/update_field/:id' => 'gcps#update_field', :as => "update_field_gcp"
  
  
  post '/gcps/add_many' => 'gcps#add_many', :as => 'add_many_gcps'
  post '/gcps/add_many/:mapid' => 'gcps#add_many_to_map', :as => 'add_many_gcps_to_map'

  get '/maps/wms/:id' => "maps#wms", :as => 'wms_map'
  get '/maps/tile/:id/:z/:x/:y' => "maps#tile", :as => 'tile_map'
  get '/maps/tile/:id' => "maps#tile", :as => 'tile_map_base'
  
  get '/mosaics/wms/:id' => "layers#wms", :as => "wms_layer"
  get '/mosaics/wms' => "layers#wms", :as => "wms_layer_base"
  get '/mosaics/tile/:id/:z/:x/:y' => "layers#tile", :as => 'tile_layer'
  get '/mosaics/tile/:id' => "layers#tile", :as => 'tile_layer_base'
 
  get '/layers/wms/:id' => "layers#wms"
  get '/layers/wms' => "layers#wms"
  get '/layers/tile/:id/:z/:x/:y' => "layers#tile"
  get '/layers/tile/:id' => "layers#tile"

  resources :layers do
    member do
      get 'comments'
      get 'merge'
      get 'publish'
      get 'toggle_visibility'
      patch 'update_year'
      get 'wms'
      get 'wms2'
      get 'maps'
      get 'export'
      get 'metadata'
      get 'delete'
      get 'id'
      get 'trace'
      get 'idland'
    end
    collection do 
      get 'geosearch'
    end
  end
  
  put '/layers/:id/remove_map/:map_id' => 'layers#remove_map', :as => 'remove_layer_map'
  put '/layers/:id/merge' => 'layers#merge', :as => 'do_merge_layer'
  
  get '/users/:user_id/maps' => 'my_maps#list', :as => 'my_maps'
  post '/users/:user_id/maps/create/:map_id' => 'my_maps#create', :as => 'add_my_map'
  post '/users/:user_id/maps/destroy/:map_id' => 'my_maps#destroy', :as => 'destroy_my_map'

  get '/users/:id/activity' => 'audits#for_user', :as => 'user_activity'
  
  
  get '/maps/acitvity.:format' => 'audits#for_map_model', :as => "formatted_maps_activity"
  get '/maps/:id/activity' => 'audits#for_map', :as => "map_activity"
  get '/maps/:id/activity.:format' => 'audits#for_map', :as => "formatted_map_activity"

  get '/activity' => 'audits#index', :as => "activity"
  get '/activity/:id' => 'audits#show', :as => "activity_details"
  get '/activity.:format' => 'audits#index', :as => "formatted_activity"

  
  resources :comments

  
  resources :groups 
  
  get '/groups/:group_id/users/new' => 'memberships#new', :as => 'new_group_user'
  delete '/groups/:group_id/users/destroy/:id' => 'memberships#destroy', :as => 'destroy_group_user'
  get '/groups/:group_id/users' => 'users#index_for_group', :as => 'group_users'
  get '/groups/:group_id/map' => 'maps#index_for_map', :as => 'group_maps'

  resources :imports do
    member do
      get 'maps'
      get 'start'
      get 'status'
      get 'log'
    end
  end
  
  get 'exports' => 'imports#exports'
  
  get '/search' => 'home#search', :as => 'search'
   
  namespace :api do
    namespace :v1 do
      get '/' =>  'api#index'
      constraints defaults: {format: "json"} do
        resources :maps, :except => [:new] do
          member do
            get    'gcps'
            patch  'rectify'
            post   'mask'
            delete 'mask'   => 'maps#delete_mask'
            patch  'crop'   
            patch  'mask_crop_rectify'
            patch  'publish'
            patch  'unpublish'
            get    'status'
          end
          resources :layers, :only => [:index]
        end
  
        resources :layers, :except => [:new] do
          member do
            patch 'toggle_visibility'
            patch 'remove_map'
            patch 'merge'
          end
          collection do
          end
          resources :maps, :only => [:index]
        end
        
      end
      constraints  defaults: {format: "json"} do
        
        resources :gcps, :except => [:new] do
          collection do
            post 'add_many'
          end
        end
        
        resources :users, :only => [:show, :index]

        
        get 'stats' =>              'activity#stats'
        get 'activity' =>           'activity#index'
        get 'activity/maps' =>      'activity#map_index'
        get 'activity/users/:id' => 'activity#for_user'
        get 'activity/maps/:id' =>  'activity#for_map'
        get 'activity/:id' =>       'activity#show'
        
        devise_scope :user do
          get    'auth/validate_token' => 'sessions#validate_token'
          post   'auth/sign_in'        => 'sessions#create'
          delete 'auth/sign_out'       => 'sessions#destroy'
        end
        
      end
    end
  end
  

end

app/controllers/api/v1/maps_controller.rb
class Api::V1::MapsController < Api::V1::ApiController
  before_filter :authenticate_user!,       :except=>[:show, :index, :status, :gcps] 
  before_filter :check_administrator_role, :only => [:publish, :unpublish]
  before_filter :find_map, :only => [:show, :update, :destroy, :gcps, :rectify, :mask, :delete_mask, :crop, :mask_crop_rectify, :publish, :unpublish, :status ]
  before_filter :can_edit_map,             :only => [:update, :destroy]
  
  before_filter :validate_jsonapi_type,:only => [:create, :update]
  
  rescue_from ActiveRecord::RecordNotFound, :with => :not_found
  rescue_from ActionController::ParameterMissing, with: :missing_param_error
  
  def show
    if request.format == "geojson"
      render :json  => @map, :serializer => MapGeoSerializer, :adapter => :attributes
     return
   end
    render :json  => @map, :include => ['layers', 'owner']
  end

  def create
    @map = Map.new(map_params)

    if user_signed_in?
      @map.owner = current_user
      @map.users << current_user
    end

    if @map.save
      render :json => @map, :status => :created
    else
      render :json => @map, :status => :unprocessable_entity, :serializer => ActiveModel::Serializer::ErrorSerializer 
    end

  end

  def update
    update_params = map_params.extract!(:upload, :upload_url)

    if @map.update_attributes(map_params)
      render :json => @map
    else
      render :json => @map, :status => :unprocessable_entity, :serializer => ActiveModel::Serializer::ErrorSerializer 
    end
  end

  def destroy
    if @map.destroy
      render :json => @map
    end
  end

  def gcps
    render :json  => @map.gcps_with_error, :meta => {"map_error"=>@map.error}
  end
  
  #patch warp
  def rectify
    resample_param = params[:resample_options]
    transform_param = params[:transform_options]
    masking_option = params[:mask]
    resample_option = ""
    transform_option = ""
    case transform_param
    when "auto"
      transform_option = ""
    when "p1"
      transform_option = " -order 1 "
    when "p2"
      transform_option = " -order 2 "
    when "p3"
      transform_option = " -order 3 "
    when "tps"
      transform_option = " -tps "
    else
      transform_option = ""
    end

    case resample_param
    when "near"
      resample_option = " -rn "
    when "bilinear"
      resample_option = " -rb "
    when "cubic"
      resample_option = " -rc "
    when "cubicspline"
      resample_option = " -rcs "
    when "lanczos" #its very very slow
      resample_option = " -rn "
    else
      resample_option = " -rn"
    end
    
    use_mask = params[:use_mask]
    if @map.gcps.hard.size.nil? || @map.gcps.hard.size < 3
      render :json => { :errors => [{:title => "Not enough gcps", :detail => "Map needs at least 3 control points to rectify"}] },:status => :unprocessable_entity
      return false
    end
    if @map.status == :warping
      render :json => { :errors => [{:title => "Map busy", :detail => "Map currently being rectified. Try again later."}] },:status => :unprocessable_entity
      return false
    end
     
    @map.warp! transform_option, resample_option, use_mask
    
    @map.clear_cache
    
    if user_signed_in?
      begin
        @map.update_commons_page(current_user)
      rescue => e
        logger.error "ERROR with update commons page Map:#{@map.id}"
        logger.error e.inspect
      end
    end
    
    render :json => @map
  end

  #post saves the mask
  def mask
    if @map.save_mask(params[:output])
      render :json => @map
    else
      render :json => { :errors => [{:title => "Mask error", :detail => "Error with saving mask"}] },:status => :unprocessable_entity
    end
  end
  
  def delete_mask
    if @map.delete_mask
      render :json => @map
    else
      render :json => {:errors =>  [{:title => "Mask error", :detail => "Error with deleting mask"}] },:status => :unprocessable_entity
    end
  end
  
  def crop
    unless  File.exists?(@map.masking_file_gml)
      render :json => {:errors => [{:title => "Mask error", :detail => "Mask file not found"}]},:status => :unprocessable_entity
      return false
    end
    if @map.mask!
      render :json => @map
    else
      render :json => { :errors => [{:title => "Mask error", :detail => "Error with cropping map"}] },:status => :unprocessable_entity
    end
  end
    
  #1. save mask
  #2. mask map
  #3. forward on to rectify
  def mask_crop_rectify
    if @map.save_mask(params[:output]) && @map.mask!
      params[:use_mask] = "true"
      rectify
    else
      render :json => { :errors => [{:title => "Saving and masking error", :detail => "Error with saving and masking map"}] },:status => :unprocessable_entity
    end
  end
  
  def publish
    unless @map.status == :warped
      render :json => {:errors => [{:title =>"Map not warped", :detail => "Map is not warped so cannot be published"}]},:status => :unprocessable_entity
      return false
    end
    if @map.publish
      render :json => @map
    else
      render :json => {:errors => [{:title => "Publish error", :detail => "Error with publishing map" }]},:status => :unprocessable_entity
    end
  end
  
  def unpublish
    unless @map.status == :published
      render :json => {:errors => [{:title => "Publish error", :detail => "Map is not published so cannot be unpublished"}] },:status => :unprocessable_entity
      return false
    end
    if @map.unpublish
      render :json => @map
    else
      render :json => {:errors => [{:title => "Publish error", :detail => "Error with unpublishing map"}] },:status => :unprocessable_entity
    end
  end
  
  def status
    render :text => @map.status
  end
  
  #params: page, per_page, query, field, sort_key, sort_order, field, show_warped, bbox, operation
  def index

    #if being called from layer#maps 
    layer_conditions = nil
    if index_params[:layer_id]
      layer = Layer.find(index_params[:layer_id])
      layer_conditions = {id: layer.maps.map(&:id)}
    end
    
    #sort / order 
    sort_order = "desc"
    sort_order = "asc" if index_params[:sort_order] == "asc"
    sort_key = %w(title status created_at updated_at).detect{|f| f == (index_params[:sort_key])}
    sort_key = sort_key || "updated_at"
    if sort_order == "desc"
      sort_nulls = " NULLS LAST"
    else
      sort_nulls = " NULLS FIRST"
    end
    
    order_options = "#{sort_key} #{sort_order} #{sort_nulls}"
  
    #pagination
    paginate_options = {
      :page => index_params[:page],
      :per_page => index_params[:per_page] || 50
    }

    #query
    query = index_params[:query]
    
    field = %w(tags title description status publisher authors).detect{|f| f == (index_params[:field])}
    field = field || "title"
    if query && query.strip.length > 0 && field
      query_options = ["#{field}  ~* ?", '(:punct:|^|)'+query+'([^A-z]|$)']
    else
      query_options = nil
    end

    #show_warped
    warped_options = nil
    if index_params[:show_warped] == "1"
      warped_options = { :status => [Map.status(:warped), Map.status(:published)], :map_type => Map.map_type(:is_map)  }
    end
    
    #bbox
    bbox_conditions = nil
    sort_geo = nil
    
    #extents = [-74.1710,40.5883,-73.4809,40.8485] #NYC
    if params[:bbox] && params[:bbox].split(',').size == 4
      extents  = nil
      begin
        extents = params[:bbox].split(',').collect {|i| Float(i)}
      rescue ArgumentError
        logger.debug "arg error with bbox, setting extent to defaults"
        #TODO send back error message here instead of defaults
      end
      if extents 
        bbox_poly_ary = [
          [ extents[0], extents[1] ],
          [ extents[2], extents[1] ],
          [ extents[2], extents[3] ],
          [ extents[0], extents[3] ],
          [ extents[0], extents[1] ]
        ]
        bbox_polygon = GeoRuby::SimpleFeatures::Polygon.from_coordinates([bbox_poly_ary], -1).as_ewkt
        if params[:operation] == "within"
          bbox_conditions = ["ST_Within(bbox_geom, ST_GeomFromText('#{bbox_polygon}'))"]
        else
          bbox_conditions = ["ST_Intersects(bbox_geom, ST_GeomFromText('#{bbox_polygon}'))"]
        end
        
        if params[:operation] == "intersect"
          sort_geo = "ABS(ST_Area(bbox_geom) - ST_Area(ST_GeomFromText('#{bbox_polygon}'))) ASC"
        else
          sort_geo ="ST_Area(bbox_geom) DESC"
        end
      end
      
    end
    
    
    @maps = Map.all.where(layer_conditions).where(warped_options).where(query_options).where(bbox_conditions).order(order_options).order(sort_geo).paginate(paginate_options)
    
    if request.format == "geojson"
      render :json  => @maps, :each_serializer => MapGeoSerializer, :adapter => :attributes
      return
    end
    #ActiveSupport.escape_html_entities_in_json = false
    render :json => @maps, 
      :include => ['layers', 'owner'],
      :meta => {"total_entries" => @maps.total_entries,
      "total_pages"   => @maps.total_pages}
  end

  private
  def map_params
    params.require(:data).require(:attributes).permit(:title, :description, :tag_list, :map_type, :subject_area, :unique_id, 
      :source_uri, :call_number, :publisher, :publication_place, :authors, :date_depicted, :scale,
      :metadata_projection, :metadata_lat, :metadata_lon,
      :upload_url, :upload, :issue_year ,:upload_file_name )

  end
  
  def index_params
    params.permit(:page, :per_page, :query, :field, :sort_key, :sort_order,  :show_warped, :bbox, :operation, :format, :layer_id, :id)
  end
  
  def find_map
    @map = Map.find(params[:id])
  end
  
  def can_edit_map
    unless user_signed_in? and ((current_user == @map.owner) or current_user.has_role?("editor"))
      permission_denied
    end    
  end
  

end

app/views/maps/edit.html.erb
<h2><%= t('.header') %></h2>


<%- if (current_user == @map.owner || admin_authorized?) -%>
   <p>&mdash; <%=  link_to t('.delete_link'), delete_map_path(@map)  %> &mdash; </p>
<% end %>

<%= render :partial => "form_remote", :locals => {:page => "edit"} %>
<div style="clear: both;"></div>

app/views/maps/idland.html.erb
<!DOCTYPE html>
<html><head></head>
  <body>
    <script>
      opener.authComplete(window.location.href);
      window.close();
    </script>
  </body>
</html>

app/views/maps/warp.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'select2/select2.min' %>
  <%= stylesheet_link_tag 'select2/select2.min' %>
  <script type="text/javascript" charset="utf-8">
    jQuery.fn.select2.defaults.set('language', '<%= I18n.locale.to_s %>');
  </script>

  <%= javascript_include_tag 'select2/i18n/nl' %>
  <%= javascript_tag "window._token = '#{form_authenticity_token}'" %>
  <script type="text/javascript" charset="utf-8">
    var icon_imgPath = '/assets/icons/';
    var gcp_add_url = "<%= url_for add_gcp_path :mapid=> @map %>";
    var gcp_update_url = "/gcps/update";
    var gcp_update_field_url = "/gcps/update_field";

    var from_map;
    var to_map;
    var gcp_markers = new Array(); // an array
    var map_id = '<%=h @map.id -%>';
    var title = '<%=u @map.title -%>';
    var image_width = <%= @map.width %>;
    var image_height = <%= @map.height %>;
    var wms_url = '<%= url_for :controller => 'maps', :action => 'wms', :id => @map  -%>';
    var empty_wms_url = '<%= url_for :controller => 'maps', :action => 'wms' -%>';
    var map_has_bounds = false;
    var layer_baseurl = '<%= url_for(wms_layer_base_path) %>';
    var layers_array = [<%=@other_layers.join(",")-%>];
    var map_bounds = new OpenLayers.Bounds();
  <% if @map.gcps.hard.size > 0 %>
      map_bounds = new OpenLayers.Bounds(<%=@map.bounds-%>);
      map_has_bounds = true;
      map_center = map_bounds.getCenterLonLat();
  <% end %>
    //set up jquery for the hidden tables
    jQuery(document).ready(function() {
      jQuery('#popoverNotice').hide();
      jQuery('#gcp_table_div').hide();
      jQuery('#advanced_form_options').hide();

      jQuery('#controlPointLink').click(function() {
        jQuery('#gcp_table_div').toggle('slow');
        return false;
      });
      jQuery('#advancedLink').click(function() {
        jQuery('#advanced_form_options').toggle('slow');
        return false;
      });
      jQuery('#to_map_notify_close>a').click(function() {
        jQuery('#to_map_notification').hide('slow');
        return false;
      });
    });

  </script>
  <%= javascript_include_tag 'helmerttransform.js' %> 
  <%= javascript_include_tag "warp"-%>

  <script  type="text/javascript">
    function popul() {
  <% @gcps.each do |gcp| -%>
        populate_gcps(<%=gcp.id-%>, <%= gcp.x -%>, <%= gcp.y -%>, <%= gcp.lon -%>, <%= gcp.lat -%>, <%=gcp.error -%>);
  <% end -%>
      update_row_numbers();

  <% if @bestguess_places -%>
        var bestGuessResult = <%= @bestguess_places.to_json.html_safe -%>;
        bestGuess(bestGuessResult);
  <% end -%>

    }
    function csv_upload() {
      jQuery("#upload_csv_form").append(jQuery("#file").clone()).hide();
      jQuery("#upload_csv_form").submit();
    }
    
    function showShortcuts(){
      var dialog = jQuery("#keyboard_shortcuts").dialog({
      bgiframe: true,
      height: 420,
      width: 480,
      resizable: false,
      draggable: false,
      modal: true,
      hide: 'slow',
      title: '<%= t('.shortcuts_title') %>',
      buttons: [{
          text: '<%= t('.close_popup') %>',
          click: function () {
            dialog.dialog("close");
          }
        }],
        open: function(){
          dialogOpen = true;
        },
        close: function () {
          dialogOpen = false;
        }
      });
    }
    
  </script>

<% end -%>

<% @onload="init();popul();" -%>

<div id ="from_map_block">
  <div id="from_map" class="map-off"></div>
  <span class="tie_button"></span>
</div>
  
<div id="between-maps-container">
<div id="link-map-button" class="link-map-button-off"
     onclick="toggleJoinLinks();" title="<%= t('.pan_lock') %>" ></div>
  
  <div id="keyboard-icon-div" onclick="showShortcuts();" >
    <%= image_tag("icons/keyboard.png", :width => 25, :height => 25, :title => t('.shortcuts_link')) %>
  </div>
</div>

<div id = "to_map_block">
  <div id="to_map_notification" class="hidden"><div id="to_map_notify_close"><a href="#" title="<%= t('.close_popup') %>">X</a></div><div id="to_map_notification_inner"></div> </div>
  <div id="to_map" class="map-off"></div>
  <div id="warped-slider"><div class="ui-slider-handle"></div></div>
</div>
<div id="popoverNotice" class="hidden-at-start"><%= image_tag "spinner.gif" %><span id="noticeMessage"></span></div>

<div id="keyboard_shortcuts" style="display:none;">
  <%= t('.shortcuts_html') %>
</div>

<div id="add_custom_layer" style="display:none;">
  <%= t('.custom_layer_instructions_html') %>
  <form>
    <div class="layer-select-container">
      <select class="layer-select"  data-placeholder="<%= t('.custom_layer_placeholder') %>">
      </select>
    </div>
  </form>
</div>

<div id="gcp">
  <em><%= t('.click_text_top') %></em>
  <div id="addPointDiv" class="addPoint"><input type="button" id="GcpButton" value="<%= t('.click_button') %>" onclick="set_gcp();" class="gcp_button" /></div>.
  <em><%= t('.click_text_btm') %></em></div>

<fieldset id="control_panel_fieldset">

  <legend><%= t('.panel_title') %></legend>
  <div id="rectifyNotice">
    <span id="spinner" style="display:none;"><%= image_tag 'spinner.gif' %></span><span id="gcp_notice"></span>
  </div>
  <a href="#" id="controlPointLink"><%= t('.gcps_link') %></a>
  <div id = "div_gcp_form">
    <%= form_for(:gcp, {:html => {:id => 'gcp_form'} ,  :url =>rectify_map_path(@map), :remote => true }) do |f| %>
      <div id="gcp_table_div" >
        <table id="gcp_table" class="gcpTabClass">

          <thead>
            <tr><th><%= t('.gcp_point') %></th><th><%= t('.gcp_x') %></th><th><%= t('.gcp_y') %></th><th><%= t('.gcp_lon') %></th><th><%= t('.gcp_lat') %></th><th id="errortitle"><%= t('.gcp_error') %>(<%=sprintf("%.2f",@map.error) %>)</th><th></th>
            </tr>
          </thead>
          <tbody id="gcp_list">
            <%= render(:partial => "gcps/gcp", :collection => @gcps) %>
          </tbody>
          <tfoot>
            <tr>
              <td colspan="7">
               <%= link_to image_tag("csv-20x25.png")+ t('.download_gcps'), gcps_map_url(@map, :format=>:csv) %>
              </td>
            </tr>
         
          </tfoot>
        </table>
        <input type="button" value="<%= t('.add_manually_button') %>" onclick="save_new_gcp(0, 0, 0, 0);" />
        <br />
      
        <fieldset class="gcp_upload">
          <label for="file"><%= t('.gcp_upload_label') %></label>
          <%= file_field_tag :file %>
          <input type="button" id="upload-csv-button" value="<%= t('.gcp_upload_button') %>"  />
        </fieldset>
        
      </div>

      <input type="hidden" name="map" value ="<%= @map.id %>" />
      <a href="#" id="advancedLink"><%= t('.advanced_options') %></a>
      <div id="advanced_form_options" >
        <%= t('.method_label') %>
        <select name="transform_options">
          <option value="auto" selected="selected"><%= t('.auto_method') %></option>
          <option value="p1"><%= t('.p1_method') %></option>
          <option value="p2"><%= t('.p2_method') %></option>
          <option value="p3"><%= t('.p3_method') %></option>
          <option value="tps"><%= t('.tps_method') %></option> <!-- tps could be unsuitable for this style of rectification? needs a good spread of gcps anyhow. -->
        </select>
        <br />
        <%= t('.resample_label') %>
        <select name="resample_options">
          <option value="near"><%= t('.near') %></option>
          <option value="bilinear"><%= t('.bilinear') %></option>
          <option value="cubic"><%= t('.cubic') %></option>
          <option value="cubicspline"><%= t('.cubicspline') %></option>
          <!-- <option value="lanczos"><%= t('.lanczos') %></option> this is very very slow -->
        </select>
      </div>
      <p>
        
   <script type="text/javascript">
    jQuery(document).ready(function() {
      jQuery("input#upload-csv-button").click(function(){
        jQuery("#upload_csv_form").append(jQuery("#file").clone()).hide();
        jQuery("#upload_csv_form").submit();
      });
      jQuery("form#gcp_form").submit(function( event ) {
        jQuery("#file").val("");
      });
      jQuery("form#gcp_form").bind("ajax:before", function(event, data, status, xhr) {
        if (event.target.id == "gcp_form"){
          bigModalDialog('<%= t('.rectifying_notice') %>');
        }
      }).bind("ajax:error", function(){
        gcp_notice('<%= t('.server_error') %>');  
      });
    });
  </script>
        <%= f.submit t('.warp_button').html_safe, {:class  => "warp_button", :id=>"warp_button"}%>
      </p>
      <div id ="clipping_mask_buttons">

        <% if @map.mask_status.nil? || @map.mask_status == :unmasked -%>
          <%= t('.unmasked_question_html', :href => url_for(map_path(:id =>@map, :anchor=>"#{t('layouts.tabs.crop')}_tab"))) %>
          <br />
        <% end %>
          <%= t('.apply_mask_html', :href=> url_for(map_path(:id =>@map, :anchor=>"#{t('layouts.tabs.crop')}_tab"))) %>
        <label for="use_mask1">
          <input <% if @map.mask_status == :masked -%>checked<%end-%> id="use_mask1" type="radio" name="use_mask" value="true" /><%= t('.yes_mask') %>
        </label>
        <label for="use_mask2">
          <input <% if @map.mask_status == :unmasked -%>checked<%end-%> name="use_mask" id="use_mask2" type="radio" value="false" /><%= t('.no_mask') %>
        </label>
      </div>

    <% end %>
  </div>
</fieldset>


<%= form_tag add_many_gcps_to_map_path(:mapid=>@map.id), multipart: true, :id => "upload_csv_form" do %>
<% end %>