config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/about' => 'home#about', :as => 'about'
  get '/help' => 'home#help', :as => 'help'
  get '/privacy' => 'home#privacy', :as => 'privacy'
  
  devise_for :users, :path => 'u',:controllers => { :sessions => "sessions", :omniauth_callbacks => "omniauth_callbacks" }
  
  resources :users do
    member do
      put 'enable'
      put 'disable'
      put 'disable_and_reset'
      put 'force_confirm'
    end
    collection do
      get 'stats'
    end
    resource :user_account
    resources :roles
  end
  
  get '/maps/activity' => 'audits#for_map_model', :as => "maps_activity"
  
  resources :maps  do
    member do
      post 'map_type'
      get 'export'
      get 'warp'
      get 'clip'
      post 'rectify'
      get 'align'
      get 'warped'
      get 'metadata'
      get 'comments'
      get 'delete'
      get 'status'
      get 'publish'
      get 'unpublish'
      post 'save_mask_and_warp'
      delete 'delete_mask'
      post 'warp_aligned'
      get 'gcps'
      get 'rough_state' => 'maps#get_rough_state'
      post 'rough_state' => 'maps#set_rough_state'
      get 'rough_centroid'=> 'maps#get_rough_centroid'
      post 'rough_centroid' => 'maps#set_rough_centroid'
      get 'id'
      get 'trace'
      get 'idland'
    end
    collection do
        get 'geosearch'
        get 'tag'
        get 'csv'
    end
    resources :layers
  end
  
  get '/maps/tag/:query' => 'maps#tag', :as => "map_tag"
  
  get '/mapimages/:id.gml.ol' => 'maps#get_mask', :as => "masking_map"
  get '/maps/thumb/:id' => 'maps#thumb', :as =>'thumb_map'
  get '/maps/thumb' => 'maps#thumb', :as => 'map_thumb_base'
  get '/layers/thumb' => 'layers#thumb', :as => 'layer_thumb_base'
  get '/mosaics/thumb/:id' => 'layers#thumb', :as =>'thumb_layer'
  get '/layers/thumb/:id' => 'layers#thumb'
 
  
  get '/gcps/bulk_import' => 'gcps#bulk_import', :as => "bulk_import_gcps"
  get '/gcps/csv' => 'gcps#csv', :as =>'csv_gcps'
  get '/gcps/:id' => 'gcps#show', :as => "gcp"
  delete '/gcps/:id/destroy' => 'gcps#destroy', :as => "destroy_gcp"
  post '/gcps/add/:mapid' => 'gcps#add', :as => "add_gcp"
  put '/gcps/update/:id' => 'gcps#update', :as => "update_gcp"
  put '/gcps/update_field/:id' => 'gcps#update_field', :as => "update_field_gcp"
  
  
  post '/gcps/add_many' => 'gcps#add_many', :as => 'add_many_gcps'
  post '/gcps/add_many/:mapid' => 'gcps#add_many_to_map', :as => 'add_many_gcps_to_map'

  get '/maps/wms/:id' => "maps#wms", :as => 'wms_map'
  get '/maps/tile/:id/:z/:x/:y' => "maps#tile", :as => 'tile_map'
  get '/maps/tile/:id' => "maps#tile", :as => 'tile_map_base'
  
  get '/mosaics/wms/:id' => "layers#wms", :as => "wms_layer"
  get '/mosaics/wms' => "layers#wms", :as => "wms_layer_base"
  get '/mosaics/tile/:id/:z/:x/:y' => "layers#tile", :as => 'tile_layer'
  get '/mosaics/tile/:id' => "layers#tile", :as => 'tile_layer_base'
 
  get '/layers/wms/:id' => "layers#wms"
  get '/layers/wms' => "layers#wms"
  get '/layers/tile/:id/:z/:x/:y' => "layers#tile"
  get '/layers/tile/:id' => "layers#tile"

  resources :layers do
    member do
      get 'comments'
      get 'merge'
      get 'publish'
      get 'toggle_visibility'
      patch 'update_year'
      get 'wms'
      get 'wms2'
      get 'maps'
      get 'export'
      get 'metadata'
      get 'delete'
      get 'id'
      get 'trace'
      get 'idland'
    end
    collection do 
      get 'geosearch'
    end
  end
  
  put '/layers/:id/remove_map/:map_id' => 'layers#remove_map', :as => 'remove_layer_map'
  put '/layers/:id/merge' => 'layers#merge', :as => 'do_merge_layer'
  
  get '/users/:user_id/maps' => 'my_maps#list', :as => 'my_maps'
  post '/users/:user_id/maps/create/:map_id' => 'my_maps#create', :as => 'add_my_map'
  post '/users/:user_id/maps/destroy/:map_id' => 'my_maps#destroy', :as => 'destroy_my_map'

  get '/users/:id/activity' => 'audits#for_user', :as => 'user_activity'
  
  
  get '/maps/acitvity.:format' => 'audits#for_map_model', :as => "formatted_maps_activity"
  get '/maps/:id/activity' => 'audits#for_map', :as => "map_activity"
  get '/maps/:id/activity.:format' => 'audits#for_map', :as => "formatted_map_activity"

  get '/activity' => 'audits#index', :as => "activity"
  get '/activity/:id' => 'audits#show', :as => "activity_details"
  get '/activity.:format' => 'audits#index', :as => "formatted_activity"

  
  resources :comments

  
  resources :groups 
  
  get '/groups/:group_id/users/new' => 'memberships#new', :as => 'new_group_user'
  delete '/groups/:group_id/users/destroy/:id' => 'memberships#destroy', :as => 'destroy_group_user'
  get '/groups/:group_id/users' => 'users#index_for_group', :as => 'group_users'
  get '/groups/:group_id/map' => 'maps#index_for_map', :as => 'group_maps'

  resources :imports do
    member do
      get 'maps'
      get 'start'
      get 'status'
      get 'log'
    end
  end
  
  get 'exports' => 'imports#exports'
  
  get '/search' => 'home#search', :as => 'search'
   
  namespace :api do
    namespace :v1 do
      get '/' =>  'api#index'
      constraints defaults: {format: "json"} do
        resources :maps, :except => [:new] do
          member do
            get    'gcps'
            patch  'rectify'
            post   'mask'
            delete 'mask'   => 'maps#delete_mask'
            patch  'crop'   
            patch  'mask_crop_rectify'
            patch  'publish'
            patch  'unpublish'
            get    'status'
          end
          resources :layers, :only => [:index]
        end
  
        resources :layers, :except => [:new] do
          member do
            patch 'toggle_visibility'
            patch 'remove_map'
            patch 'merge'
          end
          collection do
          end
          resources :maps, :only => [:index]
        end
        
      end
      constraints  defaults: {format: "json"} do
        
        resources :gcps, :except => [:new] do
          collection do
            post 'add_many'
          end
        end
        
        resources :users, :only => [:show, :index]

        
        get 'stats' =>              'activity#stats'
        get 'activity' =>           'activity#index'
        get 'activity/maps' =>      'activity#map_index'
        get 'activity/users/:id' => 'activity#for_user'
        get 'activity/maps/:id' =>  'activity#for_map'
        get 'activity/:id' =>       'activity#show'
        
        devise_scope :user do
          get    'auth/validate_token' => 'sessions#validate_token'
          post   'auth/sign_in'        => 'sessions#create'
          delete 'auth/sign_out'       => 'sessions#destroy'
        end
        
      end
    end
  end
  

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApiController
  before_filter :authenticate_user!
  before_filter :check_administrator_role, :except => [:show]
  
  rescue_from ActiveRecord::RecordNotFound, :with => :not_found

  def show
    @user = User.find(params[:id])
    render :json => @user, :include => ['roles']
  end
  
  def index
    sort_order = "desc"
    sort_order = "asc" if index_params[:sort_order] == "asc"
    sort_key = %w(login email created_at enabled provider).detect{|f| f == (index_params[:sort_key])}
    sort_key = sort_key || "updated_at" if sort_order == "desc"

    order_options = "#{sort_key} #{sort_order}"

    @query = params[:query]
    @field = %w(login email provider).detect{|f| f == (params[:field])}
    if @query && @query.strip.length > 0 && @field
      conditions = ["#{@field}  ~* ?", '(:punct:|^|)'+@query+'([^A-z]|$)']
    else
      conditions = nil
    end
    @users = User.where(conditions).order(order_options).paginate(:page=> params[:page], :per_page => 30)
    render :json => @users, :include => ['roles']
  end
  
  private
  def index_params
    params.permit(:page, :per_page, :query, :field, :sort_key, :sort_order, :field,  :format)
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'application'
  
  before_filter :authenticate_user!, :only => [:show, :edit, :update]

  before_filter :check_super_user_role, :only => [:index, :destroy, :enable, :disable, :stats, :disable_and_reset, :force_confirm]

  rescue_from ActiveRecord::RecordNotFound, :with => :bad_record
  
  helper :sort
  include SortHelper

  def stats
    sort_init "total_count"
    sort_update

    @html_title = t('.title')

    the_sql = "select user_id, username, COUNT(user_id) as total_count,
      COUNT(case when auditable_type='Gcp' then 1 end) as gcp_count,

      COUNT(case when auditable_type='Map' or auditable_type='Mapscan' then 1 end) as map_count,

      COUNT(case when action='update' and auditable_type='Gcp' then 1 end) as gcp_update_count,

      COUNT(case when action='create' and auditable_type='Gcp' then 1 end) as gcp_create_count,

      COUNT(case when action='destroy' and auditable_type='Gcp' then 1 end) as gcp_destroy_count

      from audits group by user_id, username ORDER BY #{sort_clause}"


    @users_activity = Audited::Adapters::ActiveRecord::Audit.paginate_by_sql(the_sql,
                                               :page => params[:page],
                                               :per_page => 30)
  end


  def index
    @html_title = t('.title')
    sort_init 'email'
    sort_update
    @query = params[:query]
    @field = %w(login email provider).detect{|f| f == (params[:field])}
    if @query && @query.strip.length > 0 && @field
      conditions = ["#{@field}  ~* ?", '(:punct:|^|)'+@query+'([^A-z]|$)']
    else
      conditions = nil
    end
    @users = User.where(conditions).order(sort_clause).paginate(:page=> params[:page], :per_page => 50)

  end

  def index_for_group
    @group = Group.find(params[:group_id])
    @html_title = "Users in Group " + @group.id.to_s
    sort_init 'email'
    sort_update
    @query = params[:query]
    @field = %w(login email provider).detect{|f| f == (params[:field])}
    if @query && @query.strip.length > 0 && @field
      conditions = ["#{@field}  ~* ?", '(:punct:|^|)'+@query+'([^A-z]|$)']
    else
      conditions = nil
    end
    @users = @group.users.where(conditions).order(sort_clause).paginate(:page=> params[:page],
      :per_page => 30)
    render :action => 'index'
  end

  def show
    @user = User.find(params[:id]) || current_user
    @html_title = t('.title', user_name: @user.login.capitalize)
    @mymaps = @user.maps.order("updated_at DESC").paginate(:page => params[:page],:per_page => 8)
    @current_user_maps = current_user.maps
    respond_to do | format |
      format.html {}
      format.js {}
      format.json {render :json => {:stat => "ok",:items => @user.to_a}.to_json(:only =>[:login, :created_at, :stat, :items, :enabled ])  }
    end

  end



  def edit
    @html_title = t('.title')
    @user = current_user
  end

  def update
    @user = User.find(current_user)
    if @user.update_attributes(params[:user])
      flash[:notice] = t('.flash')
      redirect_to :action => 'show', :id => current_user
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    unless @user.has_role?("administrator") ||  @user.has_role?("super user")
      if @user.destroy
        flash[:notice] = t('.flash')
      else
        flash[:error] = t('.error')
      end
    else
      flash[:error] = t('.admins_cannot_be_destroyed')
    end
    redirect_to :action => 'index'
  end

  def disable_and_reset
    @user = User.find(params[:id])
    if @user.provider?
      flash[:error] = t('.providers_cannot')
      return redirect_to :action => 'show'
    end
    unless @user.has_role?("administrator") ||  @user.has_role?("super user")
      generated_password = Devise.friendly_token.first(8)
      @user.password=generated_password
      @user.password_confirmation=generated_password
      
      if @user.save
        UserMailer.disabled_change_password(@user).deliver_now
        @user.send_reset_password_instructions
        flash[:notice] = t('.flash')
      else
        flash[:error] = t('.error')
      end
      
    else
      flash[:error] = t('.admins_cannot_be_disabled')
    end
    
    redirect_to :action => 'show'
  end

  def disable
    @user = User.find(params[:id])
    if @user.update_attribute(:enabled, false)
      flash[:notice] = t('.flash')
    else
      flash[:error] = t('.error')
    end
    redirect_to :action => 'index'
  end

  def enable
    @user = User.find(params[:id])
    if @user.update_attribute(:enabled, true)
      flash[:notice] = t('.flash')
    else
      flash[:error] = t('.error')
    end
    redirect_to :action => 'index'
  end
  
  def force_confirm
    @user = User.find(params[:id])
    if !@user.confirmed?
      @user.force_confirm!
      if @user.confirmed? 
        flash[:notice] = t('.flash')
      else
        flash[:error] = t('.error')
      end
    else
      flash[:notice] = t('.already_confirmed')
    end
    redirect_to :action => 'index'
  end
  
  

  def bad_record
    respond_to do | format |
      format.html do
        flash[:notice] = t('users.show.not_found')
        redirect_to root_path
      end
      format.json {render :json => {:stat => "not found", :items =>[]}.to_json, :status => 404}
    end
  end


end

app/views/users/_admin_tools.html.erb
<% if admin_authorized? && current_user != @user-%>
  <div class="user-admin">
    <%= t('users.index.email') %> : <%= @user.email -%>  <br />
    <%= t('users.index.enabled') %> : <%= @user.enabled ? 'Yes' : 'No' -%> <br />
    <%= t('users.index.confirmed') %> : <%= @user.confirmed? ? 'Yes' : 'No' -%> <br />
    <%= t('users.index.updated') %>: <%= @user.updated_at.to_s(:long) %>
    <br />
    <%= link_to(t('.delete_user'), user_path(@user.id), :method => :delete, :data => {:confirm => t('.delete_confirm')} ) -%> <%= t('.delete_hint') %> <br />
     
  
    <% if !@user.confirmed? -%>
      <%= link_to(t('.confirm'), force_confirm_user_path(@user.id), :method => :put) -%> <%= t('.confirm_hint') %>  <br />
    <% end  %>
    
    <% if @user.enabled -%>
      <%= link_to(t('users.user.disable').titlecase, disable_user_path(@user.id), :method => :put) -%>
    <% else -%>
      <%= link_to(t('users.user.enable').titlecase, enable_user_path(@user.id), :method => :put) -%>
    <% end -%> <%= t('.enable_hint') %>  <br />

<%- unless @user.provider? %>
    <%= link_to t('.reset_password'), disable_and_reset_user_path(@user.id), :method => :put %> <%= t('.reset_hint') %><br />
<% end %>

    <%= link_to t('users.user.edit_roles').titlecase, user_roles_path(@user) -%> <%= t('.roles_hint') %>
  </div>
<% end -%>

app/views/users/_user.html.erb
<tr class="<%= cycle('table0', 'table1') -%>">
  <td><%= time_ago_in_words(user.created_at) -%> ago</td>
  <td><%= time_ago_in_words(user.updated_at) -%> ago </td>
  <td><%= link_to(( user.login), user_path(user.id), :method => :get)  -%></td>
  <td><%= user.own_maps_count %></td>
  <% if admin_authorized? %>
    <td><%= number_to_human_size(user.upload_filesize_sum)  %></td>
    <td><%= number_to_human_size(user.disk_usage * 1024) if user.disk_usage && user.disk_usage > 0  %></td>
    <td><%=h user.provider -%></td>
    <td><%=h user.email -%></td>
    <td><%= user.enabled ? t('.u_yes') : t('.u_no') -%>&nbsp;
      <% unless user == current_user -%>
        <% if user.enabled -%>
          <%= link_to(t('.disable'), disable_user_path(user.id), :method => :put) -%>
        <% else -%>
          <%= link_to(t('.enable'), enable_user_path(user.id), :method => :put) -%>
        <% end -%>
      <% end -%>
      &nbsp;
    </td>
    <td>
      <%= user.confirmed? ? t('.u_yes') : t('.u_no') -%>
      <% if !user.confirmed? -%>
        <%= link_to(t('.activate'), force_confirm_user_path(user.id), :method => :put) -%>  
      <% end-%>
    </td>
    <td><%= link_to(t('.edit_roles'), user_roles_path(user))-%></td>
  <% end -%>
</tr>

app/views/users/index.html.erb
<% if admin_authorized? %>
 <%= form_tag url_for(:controller => "users"), :id=>"searchform",:name=> "searchform", :method => :get do -%>
    <%= t('.search') %>
    <select id="field" name="field">
      <%= options_for_select([ [t('.name'), "login"],
          [t('.email'), "email"],[t('.provider'), "provider"] ], @field)-%>
    </select>
    <%= t('.for') %>
    <%= text_field_tag 'query', @query -%>
    <input type="submit" value="<%= t('.button') %>" />
  <% end -%>
<% end %>
<h2><%= t('.header') %>
  <% if @group -%> in Group <%= @group.id.to_s -%>. <% end -%>
  <%if @query && @query.length > 0 %><%= t('.for_query') %> "<%=@query%>"
  <%end-%></h2>

<%= will_paginate @users %>
<table class="usertable">
  <thead>
    <tr>
      <%= sort_header_tag('created_at', :title => t('.created')) %>
      <%= sort_header_tag('updated_at', :title => t('.updated')) %>
      <%= sort_header_tag('login', :title => t('.login')) %>
      <%= sort_header_tag('own_maps_count', :title => t('.uploads_count')) %>
      <% if admin_authorized? %>  
        <%= sort_header_tag('upload_filesize_sum', :title => t('.uploads_size')) %>
        <%= sort_header_tag('disk_usage', :title => t('.disk_usage')) %>
        <%= sort_header_tag('provider', :title => t('.provider')) %>
        <%= sort_header_tag('email', :title => t('.email')) %>
        <%= sort_header_tag('enabled', :title => t('.enabled')) %>
        <%= sort_header_tag('confirmed_at', :title => t('.confirmed')) %>
        <th><%= t('.roles') %></th>
      <% end -%>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => "user", :collection => @users %>
  </tbody>
</table>
<%= will_paginate @users %>

app/views/users/show.html.erb
<%= link_to t('.back_to_maps').html_safe, maps_path %>

<h2><%= t('.user') %>: <%=h @user.login %></h2>
<%- if @user.provider %>
<p>
  <%= t('.provider_user_html', :provider_thumb => image_tag(@user.provider+'_logo.png', width: '17', height: '17'), :provider_name => @user.provider_name.titlecase) %>
<%- end %>
<p><%= t('.joined') %>: <%= @user.created_at.to_s(:long) %></p>
<h3><%= t('.profile') %></h3>
<p><%= (h @user.description).gsub("\n","<br/>") %></p>
<p><%=link_to t('.activity'), user_activity_url(:id=>@user.id) %></p>
<%= render :partial => 'users/admin_tools', :object => @user %>
<h3><%= t('.user_maps') %></h3>

<div id = "usermaps">
  <%=will_paginate @mymaps %>
  <table id="map_table" cellpadding="3">
    <thead>
      <tr>
        <th><%= t('common.map_th') %></th>
        <th><%= t('common.title_th') %></th>
        <th><%= t('common.year_th') %></th>
        <th><%= t('common.last_th') %></th>
        <th><%= t('common.status_th') %></th>
      </tr>
    </thead>
    <tbody id="results">
      <%= render :partial => 'maps/map', :collection =>  @mymaps unless @mymaps.nil? %>
    </tbody>
  </table>
  <%= will_paginate @mymaps %>
</div>

app/views/users/stats.html.erb
<h2><%= t('.header') %></h2>

<%= will_paginate @users_activity %>
<table class="usertable">
  <thead>
    <tr>
      <%= sort_header_tag('username', :title => t('users.show.user')) %>
      <%= sort_header_tag('total_count', :title => t('.total_count')) %>
      <%= sort_header_tag('map_count', :title => t('.map_count')) %>
      <%= sort_header_tag('gcp_count', :title => t('.gcp_count')) %>
      <%= sort_header_tag('gcp_create_count', :title => t('.gcp_create_count')) %>
      <%= sort_header_tag('gcp_update_count', :title => t('.gcp_update_count')) %>
      <%= sort_header_tag('gcp_destroy_count', :title => t('.gcp_destroy_count')) %>
      <th><%= t('.details') %></th>
    </tr>
  </thead>
  <tbody>

    <% @users_activity.each do | user | %>
      <tr class="<%= cycle('table0', 'table1') -%>">
        <td><% if user.user_id 
            user_name = User.select(:login).find_by_id(user.user_id).login
        %>
            <%= link_to(user_name, user_path(user.user_id))%>
          <% else %>
            <%= t('.unknown') %>
          <% end %>
          </td>
        <td><%=user.total_count %></td>
        <td><%=user.map_count %></td>
        <td><%=user.gcp_count %></td>
        <td><%=user.gcp_create_count %></td>
        <td><%=user.gcp_update_count %></td>
        <td><%=user.gcp_destroy_count %></td>
        <td>
          <% if user.user_id %>
            <%= link_to(t('users.show.activity'), user_activity_path(user.user_id)) %>
          <% else %>
          <% end %>
        </td>
      </tr>
    <% end %>

  </tbody>
</table>
<%= will_paginate @users_activity %>