config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/about' => 'home#about', :as => 'about'
  get '/help' => 'home#help', :as => 'help'
  get '/privacy' => 'home#privacy', :as => 'privacy'
  
  devise_for :users, :path => 'u',:controllers => { :sessions => "sessions", :omniauth_callbacks => "omniauth_callbacks" }
  
  resources :users do
    member do
      put 'enable'
      put 'disable'
      put 'disable_and_reset'
      put 'force_confirm'
    end
    collection do
      get 'stats'
    end
    resource :user_account
    resources :roles
  end
  
  get '/maps/activity' => 'audits#for_map_model', :as => "maps_activity"
  
  resources :maps  do
    member do
      post 'map_type'
      get 'export'
      get 'warp'
      get 'clip'
      post 'rectify'
      get 'align'
      get 'warped'
      get 'metadata'
      get 'comments'
      get 'delete'
      get 'status'
      get 'publish'
      get 'unpublish'
      post 'save_mask_and_warp'
      delete 'delete_mask'
      post 'warp_aligned'
      get 'gcps'
      get 'rough_state' => 'maps#get_rough_state'
      post 'rough_state' => 'maps#set_rough_state'
      get 'rough_centroid'=> 'maps#get_rough_centroid'
      post 'rough_centroid' => 'maps#set_rough_centroid'
      get 'id'
      get 'trace'
      get 'idland'
    end
    collection do
        get 'geosearch'
        get 'tag'
        get 'csv'
    end
    resources :layers
  end
  
  get '/maps/tag/:query' => 'maps#tag', :as => "map_tag"
  
  get '/mapimages/:id.gml.ol' => 'maps#get_mask', :as => "masking_map"
  get '/maps/thumb/:id' => 'maps#thumb', :as =>'thumb_map'
  get '/maps/thumb' => 'maps#thumb', :as => 'map_thumb_base'
  get '/layers/thumb' => 'layers#thumb', :as => 'layer_thumb_base'
  get '/mosaics/thumb/:id' => 'layers#thumb', :as =>'thumb_layer'
  get '/layers/thumb/:id' => 'layers#thumb'
 
  
  get '/gcps/bulk_import' => 'gcps#bulk_import', :as => "bulk_import_gcps"
  get '/gcps/csv' => 'gcps#csv', :as =>'csv_gcps'
  get '/gcps/:id' => 'gcps#show', :as => "gcp"
  delete '/gcps/:id/destroy' => 'gcps#destroy', :as => "destroy_gcp"
  post '/gcps/add/:mapid' => 'gcps#add', :as => "add_gcp"
  put '/gcps/update/:id' => 'gcps#update', :as => "update_gcp"
  put '/gcps/update_field/:id' => 'gcps#update_field', :as => "update_field_gcp"
  
  
  post '/gcps/add_many' => 'gcps#add_many', :as => 'add_many_gcps'
  post '/gcps/add_many/:mapid' => 'gcps#add_many_to_map', :as => 'add_many_gcps_to_map'

  get '/maps/wms/:id' => "maps#wms", :as => 'wms_map'
  get '/maps/tile/:id/:z/:x/:y' => "maps#tile", :as => 'tile_map'
  get '/maps/tile/:id' => "maps#tile", :as => 'tile_map_base'
  
  get '/mosaics/wms/:id' => "layers#wms", :as => "wms_layer"
  get '/mosaics/wms' => "layers#wms", :as => "wms_layer_base"
  get '/mosaics/tile/:id/:z/:x/:y' => "layers#tile", :as => 'tile_layer'
  get '/mosaics/tile/:id' => "layers#tile", :as => 'tile_layer_base'
 
  get '/layers/wms/:id' => "layers#wms"
  get '/layers/wms' => "layers#wms"
  get '/layers/tile/:id/:z/:x/:y' => "layers#tile"
  get '/layers/tile/:id' => "layers#tile"

  resources :layers do
    member do
      get 'comments'
      get 'merge'
      get 'publish'
      get 'toggle_visibility'
      patch 'update_year'
      get 'wms'
      get 'wms2'
      get 'maps'
      get 'export'
      get 'metadata'
      get 'delete'
      get 'id'
      get 'trace'
      get 'idland'
    end
    collection do 
      get 'geosearch'
    end
  end
  
  put '/layers/:id/remove_map/:map_id' => 'layers#remove_map', :as => 'remove_layer_map'
  put '/layers/:id/merge' => 'layers#merge', :as => 'do_merge_layer'
  
  get '/users/:user_id/maps' => 'my_maps#list', :as => 'my_maps'
  post '/users/:user_id/maps/create/:map_id' => 'my_maps#create', :as => 'add_my_map'
  post '/users/:user_id/maps/destroy/:map_id' => 'my_maps#destroy', :as => 'destroy_my_map'

  get '/users/:id/activity' => 'audits#for_user', :as => 'user_activity'
  
  
  get '/maps/acitvity.:format' => 'audits#for_map_model', :as => "formatted_maps_activity"
  get '/maps/:id/activity' => 'audits#for_map', :as => "map_activity"
  get '/maps/:id/activity.:format' => 'audits#for_map', :as => "formatted_map_activity"

  get '/activity' => 'audits#index', :as => "activity"
  get '/activity/:id' => 'audits#show', :as => "activity_details"
  get '/activity.:format' => 'audits#index', :as => "formatted_activity"

  
  resources :comments

  
  resources :groups 
  
  get '/groups/:group_id/users/new' => 'memberships#new', :as => 'new_group_user'
  delete '/groups/:group_id/users/destroy/:id' => 'memberships#destroy', :as => 'destroy_group_user'
  get '/groups/:group_id/users' => 'users#index_for_group', :as => 'group_users'
  get '/groups/:group_id/map' => 'maps#index_for_map', :as => 'group_maps'

  resources :imports do
    member do
      get 'maps'
      get 'start'
      get 'status'
      get 'log'
    end
  end
  
  get 'exports' => 'imports#exports'
  
  get '/search' => 'home#search', :as => 'search'
   
  namespace :api do
    namespace :v1 do
      get '/' =>  'api#index'
      constraints defaults: {format: "json"} do
        resources :maps, :except => [:new] do
          member do
            get    'gcps'
            patch  'rectify'
            post   'mask'
            delete 'mask'   => 'maps#delete_mask'
            patch  'crop'   
            patch  'mask_crop_rectify'
            patch  'publish'
            patch  'unpublish'
            get    'status'
          end
          resources :layers, :only => [:index]
        end
  
        resources :layers, :except => [:new] do
          member do
            patch 'toggle_visibility'
            patch 'remove_map'
            patch 'merge'
          end
          collection do
          end
          resources :maps, :only => [:index]
        end
        
      end
      constraints  defaults: {format: "json"} do
        
        resources :gcps, :except => [:new] do
          collection do
            post 'add_many'
          end
        end
        
        resources :users, :only => [:show, :index]

        
        get 'stats' =>              'activity#stats'
        get 'activity' =>           'activity#index'
        get 'activity/maps' =>      'activity#map_index'
        get 'activity/users/:id' => 'activity#for_user'
        get 'activity/maps/:id' =>  'activity#for_map'
        get 'activity/:id' =>       'activity#show'
        
        devise_scope :user do
          get    'auth/validate_token' => 'sessions#validate_token'
          post   'auth/sign_in'        => 'sessions#create'
          delete 'auth/sign_out'       => 'sessions#destroy'
        end
        
      end
    end
  end
  

end

app/views/shared/_addthis.html.erb
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style"
     addthis:title="<%=snippet(title, 20)%>"
     addthis:description="<%=snippet(description, 30)%>" >
  <a href="http://www.addthis.com/bookmark.php?v=250&amp;username=<%=APP_CONFIG['addthis_user']%>"
     class="addthis_button_compact" >Share</a>
  <span class="addthis_separator">|</span>
  <a class="addthis_button_facebook"></a>
  <a class="addthis_button_google"></a>
  <a class="addthis_button_twitter"></a>
</div>
<script type="text/javascript" src="//s7.addthis.com/js/250/addthis_widget.js#username=<%=APP_CONFIG['addthis_user']%>"></script>
<!-- AddThis Button END -->

app/views/shared/_analytics.html.erb
<% unless APP_CONFIG['google_analytics_code'].blank? %>
<script  type="text/javascript">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= APP_CONFIG['google_analytics_code'] %>', 'auto');
  ga('send', 'pageview');
</script>
<% end %>

app/views/shared/_analyticsbottom.html.erb
<% unless APP_CONFIG['google_analytics_code'].blank? %>
<script type="text/javascript">
  try {
    <%- if @layer -%>
    ga('send', 'pageview', "layers/<%=@current_tab%>/<%=@layer.id%>");
      <%- else -%>
    ga('send', 'pageview', "maps/<%=@current_tab%>/<%=@map.id%>");
      <%- end -%>
  } catch(err) {}
</script>
<% end %>

app/views/shared/_analyticstop.html.erb
<% unless APP_CONFIG['google_analytics_code'].blank? %>
<script  type="text/javascript">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= APP_CONFIG['google_analytics_code'] %>', 'auto');
  ga('send', 'pageview');
</script>
<% end %>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
  <div id="error_explanation">
    <h2><%= t('errors.template.header', model: target.class.name.downcase, count: target.errors.messages.size) %></h2>
    <ul>
      <% target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_export_window.html.erb
<script type="text/javascript">
  var isHovering = false;
  function closeExportWindow(force) {
    if (!isHovering || force) {
      jQuery('#export_window').hide();
    }
  }
  jQuery(document).ready(function() {

    jQuery("#export_window").hide();
    jQuery("#export_button").click(function() {
      var o = jQuery(this).offset();
      jQuery("#export_window").css({'position': 'absolute', 'left': o.left, 'top': o.top + 17});
      jQuery("#export_window").show();
    });

    jQuery("#export_window").mouseenter(function() {
      isHovering = true;
    }).mouseleave(function() {
      isHovering = false;
      setTimeout('closeExportWindow(false)', 700);
    });

    jQuery("#close_export_window").click(function() {
      closeExportWindow(true);
    });

  });
</script>

<span id="export_toolbox">|&nbsp;
  <a href="#" id="export_button" class="export_button"><%=image_tag("KML-logo-20x25.png", :height => '16')%>&nbsp;<%= t('.header') %></a>
  <div id="export_window" class="export_float_div hidden" >
    <div id="export_window_inner">
      <div id="export_window_head">
        <span><%= t('.links') %></span>
        <a id="close_export_window" href="#" >X</a>
      </div>
      <div id="export_window_content" style="display: block;">
        <% unless @layer -%>
          <ul>
            <li> <%= link_to(image_tag("KML-logo-20x25.png")+t('maps.export.kml_link'),  map_url(:id => @map, :format => :kml)) %>  </li>
            <li><%= link_to(image_tag("wms-20x25.png")+t('maps.export.wms_link'),url_for(wms_map_url(:id=>@map, :request => "GetCapabilities", :service => "WMS", :version => "1.1.1")) )%> </li>
            <li>
              <% tile_url = url_for(:controller => "maps", :action => "tile", :id => @map, :x => "x", :y => "y", :z => "z", :only_path => false) %>
              <%=link_to image_tag("tiles-20x25.png")+t('maps.export.tiles'), tile_url %> 
            </li>
            <li><%= link_to image_tag("csv-20x25.png")+t('maps.export.gcp_csv_link'), gcps_map_url(@map, :format=>:csv) %></li>
            <% if user_signed_in? -%>
              <li><%= link_to(image_tag("image-icon-20x25.png")+t('maps.export.geotiff_link'), export_map_url(:id => @map, :format => :tif)) %> </li>
              <li><%= link_to(image_tag("image-icon-20x25.png")+t('maps.export.png_link'), export_map_url(:id => @map, :format => :png)) %></li>
              <li>&nbsp;</li>
            <% else -%>
              <li> Log in for</li>
            <% end -%>
            <li> <%= link_to_if(user_signed_in?, t('.more'), map_path(:id=> @map,:anchor=>"#{t('layouts.tabs.export')}_tab")) -%> </li>
          </ul>
        <% else  -%>
  <%#layer%>
          <ul>
            <li> <%= link_to(image_tag("KML-logo-20x25.png")+t('maps.export.kml_link'),  layer_url(:id => @layer, :format => :kml)) %>  </li>
            <li><%= link_to(image_tag("wms-20x25.png")+t('maps.export.wms_link'), :action=>"wms", :id=>@layer, :request => "GetCapabilities", :service => "WMS", :version => "1.1.1" )%> </li>
            <li>
              <% tile_url = url_for(:controller => "layers", :action => "tile", :x => "x", :y => "y", :z => "z", :only_path => false) %>
              <%=link_to image_tag("tiles-20x25.png")+t('maps.export.tiles'), tile_url %> 
            </li>
            <% unless user_signed_in? -%>
              <li> Log in for</li>
            <% end -%>
            <li> <%= link_to_if(user_signed_in?, t('.more'), layer_path(:id=> @layer,:anchor=>"#{t('layouts.tabs.export')}_tab")) -%> </li>

          </ul>


        <% end %>
        <div style="clear:both;"></div>
      </div>
      <div id="export_window_foot" style="display: block;">
        <%= t('common.site_title') %>
      </div>
    </div>
  </div>
</span>

app/views/shared/_footer.html.erb
<div id="nav">
  <a href="/"><%= t('.home') %></a> |
  <%= link_to t('.add_map'), new_map_path %> |
  <a href="/about.htm"><%= t('.about') %></a> |
  <a href="/help.htm"><%= t('.help') %></a> |
  <a href="/privacy.htm">Privacy</a> |
  <%= t('.supported_by_html') %>
</div>

app/views/shared/_header.html.erb
<div class="user_status">
  <% if user_signed_in? %>
    <%= t('.logged_in_as') %>
    <% if current_user.provider? %>
      <%= link_to "#{image_tag(current_user.provider+'_logo.png', width: '17', height: '17', class: 'user_provider')} #{current_user.login.capitalize}".html_safe, user_path(current_user) %>
    <% else %>
      <%= link_to h(current_user.login.capitalize), user_path(current_user) %>
    <% end %>
    <%= link_to t('.my_maps'), my_maps_path(current_user) %>
    <%= link_to t('.my_activity'), user_activity_path(current_user) %>
    <%= link_to t('.settings'), edit_user_registration_path %>
    <%= link_to t('.log_out'), destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to t('.log_in'), new_user_session_path %>
    <%= link_to t('.sign_up'), new_user_registration_path %>
  <% end %>
  <% if user_signed_in? %>
    <% if current_user.has_role?("administrator") || current_user.has_role?("super user") %>
      <br />
      <%= link_to t('.all_maps'), maps_path %>
      <%= link_to t('.all_layers'), layers_path %>
      <%= link_to t('.all_activity'), activity_path %>
      <%= link_to t('.all_comments'), comments_path %>
      <%# link_to "Groups", groups_path %>
      <%= link_to t('.imports'), imports_path %>
      <%= link_to t('.user_stats'), stats_users_path %>
      <%= link_to t('.admin_users'), users_path %>
    <% end %>
  <% end %>
  <%= render :partial => 'shared/locales' %>
</div>

app/views/shared/_locales.html.erb
<% if I18n.available_locales.length > 1 %>
  <div class="locale-switcher">
    <span class="selected-locale"><%= t('locales.' + I18n.locale.to_s) + ' (' + I18n.locale.to_s + ')' %></span>
    <ul class="selecticve-locale-items">
      <% url_base = request.url.split('?').first %>
      <% selective_locales = I18n.available_locales.select { |locale| locale != I18n.locale }  %>
      <% for locale in selective_locales do %>
        <li class="locale-item">
          <% url = I18n.default_locale == locale ? url_base : url_base + '?locale=' + locale.to_s %>
          <%= link_to t('locales.' + locale.to_s, locale: locale) + ' (' + locale.to_s + ')', url, class: 'selective-locale' %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<div id="nav">
  <ul id="navlist" class="<%= I18n.locale %>">
    <li><%= link_to_unless_current(t('.home'), root_path) { "<span>#{t('.home')}</span>".html_safe } %></li>
    <li class=""><%= link_to_unless((current_page?(maps_url) && !current_page?(maps_url(:show_warped =>1))),t('.maps'), maps_url) { "<span>#{t('.maps')}</span>".html_safe } %></li>
    <li class="responsive responsive_narrow"><%= link_to_unless_current(t('.rectified_maps'), maps_url(:show_warped =>1)) { "<span>#{t('.rectified_maps')}</span>".html_safe } %></li>    
    <li class="responsive responsive_wide"><%= link_to_unless_current(t('.geosearch_maps'), geosearch_maps_url(:show_warped =>1)) { "<span>#{t('.geosearch_maps')}</span>".html_safe } %></li>    
    <li class="responsive"><%= link_to_unless_current(t('.add_map'), new_map_path) { "<span>#{t('.add_map')}</span>".html_safe } %></li>
    <li class="responsive"><%= link_to_unless_current(t('.layers'),  layers_path) { "<span>#{t('.layers')}</span>".html_safe } %></li>
    <li class="responsive responsive_wide"><%= link_to_unless_current(t('.geosearch_layers'),  geosearch_layers_url) { "<span>#{t('.geosearch_layers')}</span>".html_safe } %></li>    
    <li class="responsive responsive_narrow"><%= link_to_unless_current(t('.add_layer'), new_layer_path) { "<span>#{t('.add_layer')}</span>".html_safe } %></li>
    <li class="responsive responsive_narrow"><%= link_to_unless_current(t('.about'), about_path) { "<span>#{t('.about')}</span>".html_safe } %></li>
    <li class="responsive responsive_narrow"><%= link_to_unless_current(t('.help'), help_path) { "<span>#{t('.help')}</span>".html_safe } %></li>
  </ul>
</div>

app/views/shared/_search.html.erb
<%= form_tag url_for(:controller => "maps"), :id=>"searchform",:name=> "searchform", :method => :get do -%>
  <%= t('.search') %>  
  <select id="field" name="field">
    <%= options_for_select([ [t('.title'), "title"], 
            [t('.description'), "description"], 
        [t('.publisher'), "publisher"],
        [t('.author'), "authors"],
        [t('.tags'), "tags"]], @field)-%>
  </select>
  <%= t('.for') %> 
  <%= text_field_tag 'query', @query -%>
  <input type="hidden" id="from" />
  <input type="hidden" id="to"/>
  
  <div id="year-filter">
    <div id="year-label">
      <%= t('common.year_th') %>
    </div>
    <div id="year-slider-container">
      <div id="year-slider"></div>
    </div>	
  </div>
  
  <input type="submit" value="<%= t('.button') %>">
  <% if @show_warped == "1" -%>
    <% check_all = false -%>
    <% check_rectified = true -%>
  <% else -%>
    <% check_all = true -%>
    <% check_rectified = false -%>
  <% end %>
  <div id="radio-buttons">
    <label for="all_maps"><%= t('.all_maps') %></label>
    <%= radio_button_tag('show_warped', 0, check_all, :id => 'all_maps') %>
    <label for="rectified_maps"><%= t('.only_rectified') %></label>
    <%= radio_button_tag('show_warped', 1, check_rectified, :id => 'rectified_maps') %>
 </div>

  <script>
    var year_from = <%= params[:from] || @year_min.to_i %>;
    var year_to = <%= params[:to] || @year_max.to_i %>;
  jQuery("#year-slider").noUiSlider({
    start: [year_from, year_to],
    connect: true,
    step: 1,
    format: wNumb({
      decimals: 0
    }),
    range: {
      'min': <%=  @year_min.to_i %>,
      'max': <%= @year_max.to_i %>
    }
    });
    
    jQuery("#year-slider").Link('upper').to('-inline-<div class="year-slider-tooltip"></div>', function ( value ) {
      jQuery(this).html(
        '<span>' + value + '</span>'
      );
    });
       
    jQuery("#year-slider").Link('lower').to('-inline-<div class="year-slider-tooltip"></div>', function ( value ) {
      jQuery(this).html(
        '<span>' + value + '</span>'
      );
    });
    
    jQuery("#year-slider").Link('upper').to('to')
    jQuery("#year-slider").Link('lower').to('from')

   </script>	
<% end -%>
<div id="geosearch-link">
  <%= link_to t('.find_geosearch'),  url_for(:controller => 'maps', :action=>'geosearch'), :class => "buttonWarper" %>
</div>

app/views/shared/_sort.html.erb
Sort By:
<%= sort_header_tag('title', :title => t('common.title_th')) %>
&nbsp;|&nbsp;
<%= sort_header_tag('issue_year', :title => t('common.year_th')) %>
&nbsp;|&nbsp;
<%= sort_header_tag('updated_at', :title => t('common.last_th')) %>
&nbsp;|&nbsp;
<%= sort_header_tag('status', :title => t('common.status_th')) %>