config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/about' => 'home#about', :as => 'about'
  get '/help' => 'home#help', :as => 'help'
  get '/privacy' => 'home#privacy', :as => 'privacy'
  
  devise_for :users, :path => 'u',:controllers => { :sessions => "sessions", :omniauth_callbacks => "omniauth_callbacks" }
  
  resources :users do
    member do
      put 'enable'
      put 'disable'
      put 'disable_and_reset'
      put 'force_confirm'
    end
    collection do
      get 'stats'
    end
    resource :user_account
    resources :roles
  end
  
  get '/maps/activity' => 'audits#for_map_model', :as => "maps_activity"
  
  resources :maps  do
    member do
      post 'map_type'
      get 'export'
      get 'warp'
      get 'clip'
      post 'rectify'
      get 'align'
      get 'warped'
      get 'metadata'
      get 'comments'
      get 'delete'
      get 'status'
      get 'publish'
      get 'unpublish'
      post 'save_mask_and_warp'
      delete 'delete_mask'
      post 'warp_aligned'
      get 'gcps'
      get 'rough_state' => 'maps#get_rough_state'
      post 'rough_state' => 'maps#set_rough_state'
      get 'rough_centroid'=> 'maps#get_rough_centroid'
      post 'rough_centroid' => 'maps#set_rough_centroid'
      get 'id'
      get 'trace'
      get 'idland'
    end
    collection do
        get 'geosearch'
        get 'tag'
        get 'csv'
    end
    resources :layers
  end
  
  get '/maps/tag/:query' => 'maps#tag', :as => "map_tag"
  
  get '/mapimages/:id.gml.ol' => 'maps#get_mask', :as => "masking_map"
  get '/maps/thumb/:id' => 'maps#thumb', :as =>'thumb_map'
  get '/maps/thumb' => 'maps#thumb', :as => 'map_thumb_base'
  get '/layers/thumb' => 'layers#thumb', :as => 'layer_thumb_base'
  get '/mosaics/thumb/:id' => 'layers#thumb', :as =>'thumb_layer'
  get '/layers/thumb/:id' => 'layers#thumb'
 
  
  get '/gcps/bulk_import' => 'gcps#bulk_import', :as => "bulk_import_gcps"
  get '/gcps/csv' => 'gcps#csv', :as =>'csv_gcps'
  get '/gcps/:id' => 'gcps#show', :as => "gcp"
  delete '/gcps/:id/destroy' => 'gcps#destroy', :as => "destroy_gcp"
  post '/gcps/add/:mapid' => 'gcps#add', :as => "add_gcp"
  put '/gcps/update/:id' => 'gcps#update', :as => "update_gcp"
  put '/gcps/update_field/:id' => 'gcps#update_field', :as => "update_field_gcp"
  
  
  post '/gcps/add_many' => 'gcps#add_many', :as => 'add_many_gcps'
  post '/gcps/add_many/:mapid' => 'gcps#add_many_to_map', :as => 'add_many_gcps_to_map'

  get '/maps/wms/:id' => "maps#wms", :as => 'wms_map'
  get '/maps/tile/:id/:z/:x/:y' => "maps#tile", :as => 'tile_map'
  get '/maps/tile/:id' => "maps#tile", :as => 'tile_map_base'
  
  get '/mosaics/wms/:id' => "layers#wms", :as => "wms_layer"
  get '/mosaics/wms' => "layers#wms", :as => "wms_layer_base"
  get '/mosaics/tile/:id/:z/:x/:y' => "layers#tile", :as => 'tile_layer'
  get '/mosaics/tile/:id' => "layers#tile", :as => 'tile_layer_base'
 
  get '/layers/wms/:id' => "layers#wms"
  get '/layers/wms' => "layers#wms"
  get '/layers/tile/:id/:z/:x/:y' => "layers#tile"
  get '/layers/tile/:id' => "layers#tile"

  resources :layers do
    member do
      get 'comments'
      get 'merge'
      get 'publish'
      get 'toggle_visibility'
      patch 'update_year'
      get 'wms'
      get 'wms2'
      get 'maps'
      get 'export'
      get 'metadata'
      get 'delete'
      get 'id'
      get 'trace'
      get 'idland'
    end
    collection do 
      get 'geosearch'
    end
  end
  
  put '/layers/:id/remove_map/:map_id' => 'layers#remove_map', :as => 'remove_layer_map'
  put '/layers/:id/merge' => 'layers#merge', :as => 'do_merge_layer'
  
  get '/users/:user_id/maps' => 'my_maps#list', :as => 'my_maps'
  post '/users/:user_id/maps/create/:map_id' => 'my_maps#create', :as => 'add_my_map'
  post '/users/:user_id/maps/destroy/:map_id' => 'my_maps#destroy', :as => 'destroy_my_map'

  get '/users/:id/activity' => 'audits#for_user', :as => 'user_activity'
  
  
  get '/maps/acitvity.:format' => 'audits#for_map_model', :as => "formatted_maps_activity"
  get '/maps/:id/activity' => 'audits#for_map', :as => "map_activity"
  get '/maps/:id/activity.:format' => 'audits#for_map', :as => "formatted_map_activity"

  get '/activity' => 'audits#index', :as => "activity"
  get '/activity/:id' => 'audits#show', :as => "activity_details"
  get '/activity.:format' => 'audits#index', :as => "formatted_activity"

  
  resources :comments

  
  resources :groups 
  
  get '/groups/:group_id/users/new' => 'memberships#new', :as => 'new_group_user'
  delete '/groups/:group_id/users/destroy/:id' => 'memberships#destroy', :as => 'destroy_group_user'
  get '/groups/:group_id/users' => 'users#index_for_group', :as => 'group_users'
  get '/groups/:group_id/map' => 'maps#index_for_map', :as => 'group_maps'

  resources :imports do
    member do
      get 'maps'
      get 'start'
      get 'status'
      get 'log'
    end
  end
  
  get 'exports' => 'imports#exports'
  
  get '/search' => 'home#search', :as => 'search'
   
  namespace :api do
    namespace :v1 do
      get '/' =>  'api#index'
      constraints defaults: {format: "json"} do
        resources :maps, :except => [:new] do
          member do
            get    'gcps'
            patch  'rectify'
            post   'mask'
            delete 'mask'   => 'maps#delete_mask'
            patch  'crop'   
            patch  'mask_crop_rectify'
            patch  'publish'
            patch  'unpublish'
            get    'status'
          end
          resources :layers, :only => [:index]
        end
  
        resources :layers, :except => [:new] do
          member do
            patch 'toggle_visibility'
            patch 'remove_map'
            patch 'merge'
          end
          collection do
          end
          resources :maps, :only => [:index]
        end
        
      end
      constraints  defaults: {format: "json"} do
        
        resources :gcps, :except => [:new] do
          collection do
            post 'add_many'
          end
        end
        
        resources :users, :only => [:show, :index]

        
        get 'stats' =>              'activity#stats'
        get 'activity' =>           'activity#index'
        get 'activity/maps' =>      'activity#map_index'
        get 'activity/users/:id' => 'activity#for_user'
        get 'activity/maps/:id' =>  'activity#for_map'
        get 'activity/:id' =>       'activity#show'
        
        devise_scope :user do
          get    'auth/validate_token' => 'sessions#validate_token'
          post   'auth/sign_in'        => 'sessions#create'
          delete 'auth/sign_out'       => 'sessions#destroy'
        end
        
      end
    end
  end
  

end

app/models/import.rb
class Import < ActiveRecord::Base
  has_many :maps
  accepts_nested_attributes_for :maps,  :allow_destroy => true
  belongs_to :user, :class_name => "User"
  validates_presence_of :path
  validates_presence_of :name
  validates_presence_of :uploader_user_id
  validate :custom_validate

  before_save :count_files
  before_create :setup_import

  def start_importing
    logger.info "Starting import"
    if state == "ready"  #don't want to import maps that are already importing, or that has already been imported
      self.state = "importing"
      save!
      user = User.find_by_id(uploader_user_id)
      if Layer.exists?(layer_id)
        layer = Layer.find(layer_id)
        logger.info  "Using Layer #{layer.id.to_s}"
      elsif layer_id == -99
        layer = Layer.new(:name => layer_title)
        layer.user = user
        layer.save
        logger.info "Using New Layer #{layer.id.to_s} with title #{layer.name} "
      end

      include_exts = [".tif", ".gif", ".png", ".jpg", ".jpeg", ".tif.png", ".tiff"]
      logger.info "Starting import..."
      count = 0
      Dir.foreach(path) do | ourfilename |
        logger.info "Looking at file: #{ourfilename} "
        unless Map.exists?(:upload_file_name => ourfilename)
          title_suffix = ''
          title_suffix = ' ' + map_title_suffix unless map_title_suffix.blank?
          map = Map.new(:title => ourfilename + title_suffix,
            :description => map_description,
            :publisher => map_publisher,
            :authors => map_author)
          ourfile = File.join(path , ourfilename)

          map.owner = user
          map.users << user
          if layer
            map.layers << layer
          end

          File.open(ourfile) { |photo_file| map.upload = photo_file }
          if map.save
            self.maps << map
            count += 1
            logger.info "Imported! #{count} : #{ ourfilename.to_s}"
          else
            logger.info "Not saved..."
            if map.errors.on(:filename)
              logger.info  "Map has same name, wasn't imported: #{ourfilename.to_s} "
            end
          end

        end if include_exts.include?(File.extname(ourfilename).to_s)

      end

      self.state = "imported"
      self.imported_count = count
      save!
      logger.info "Finished Importing"
    else
      logger.info "Import not ready to be imported"
    end

  end

  def status
    status = ""
    if self.state == "importing"
      status = "Importing: #{self.maps.count} : #{self.file_count}"
    elsif self.state == "imported"
      status = "Finished: #{self.imported_count}"
    else
      status = self.state.to_s
    end
    status
  end

  protected
  #errors are activemodel.errors.model.import.
  def custom_validate
    errors.add(:layer_id, :layer_error) unless Layer.exists?(layer_id) || layer_id == nil || layer_id == -99
    errors.add(:uploader_user_id, :user_not_exist) if !User.exists?(uploader_user_id)
    errors.add(:layer_title, :blank_layer_title) if layer_title.blank? && layer_id == -99
    begin
      errors.add(:path, :path_not_exist) if !File.exists?(path)
      errors.add(:path, :no_files_error) if Dir.entries(path).size - 2 == 0
    rescue Errno::ENOENT
    end
  end
  
  def setup_import
    state = "ready"
  end
  
  def count_files
    self.file_count = Dir.entries(self.path).size - 2
  end
 

end

app/controllers/api/v1/imports_controller.rb
class Api::V1::ImportsController < Api::V1::ApiController
  before_filter :authenticate_user!
  before_filter :check_editor_role
  before_filter :find_import, :only => [:show, :update, :destroy, :start, :maps]
  
  before_filter :validate_jsonapi_type,:only => [:create, :update]
   
  rescue_from ActiveRecord::RecordNotFound, :with => :not_found
  rescue_from ActionController::ParameterMissing, with: :missing_param_error

  def show
    render :json => @import
  end
  
  def create
    @import = Import.new(import_params)
    @import.user = current_user
    @import.uploader_user_id = current_user.id
    if @import.save
      render :json => @import, :status => :created
    else
      render :json => @import, :status => :unprocessable_entity,  :serializer => ActiveModel::Serializer::ErrorSerializer 
    end
  end

  def update
    if @import.update_attributes(import_params)
      render :json => @import
    else
      render :json => @import, :status => :unprocessable_entity, :serializer => ActiveModel::Serializer::ErrorSerializer 
    end
  end

  def destroy
    if @import.destroy
      render :json => @import
    else
      render :json => { :errors => [{:title => "Import error", :detail => "Error deleting import"}] },:status => :unprocessable_entity
    end
  end

  def start
    @import.prepare_run
    Spawnling.new do
      @import.import!({:async => true})
    end
    render :json => @import
  end

  def maps
    sort_key = "created_at"
    sort_order = "desc"
    sort_order = "asc" if index_params[:sort_order] == "asc"

    order_options = "#{sort_key} #{sort_order}"
     paginate_options = {
      :page => index_params[:page],
      :per_page => index_params[:per_page] || 50
    }
    @maps = @import.maps.order(order_options).paginate(paginate_options)
    render :json => @maps
  end
  
  def index
    sort_order = "desc"
    sort_order = "asc" if index_params[:sort_order] == "asc"
    sort_key = %w(id category user_id status created_at finished_at).detect{|f| f == (index_params[:sort_key])}
    sort_key = sort_key || "created_at"

    order_options = "#{sort_key} #{sort_order}"
    
    paginate_options = {
      :page => index_params[:page],
      :per_page => index_params[:per_page] || 50
    }
    
    @imports = Import.order(order_options).paginate(paginate_options)
    render :json => @imports, :index => true
  end
  
  
  private
  def index_params
    params.permit(:page, :per_page, :sort_key, :sort_order, :format)
  end
  
  def import_params
    params.require(:data).require(:attributes).permit(:category, :save_layer)
  end

  def find_import
    @import = Import.find(params[:id])
  end
  
  
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :check_administrator_role

  before_filter :find_import, :except => [:index, :new, :create, :exports]
  before_filter :check_imported, :only => [:start]

  rescue_from ActiveRecord::RecordNotFound, :with => :bad_record
  
  helper :sort
  include SortHelper

  def index
    @imports = Import.order("updated_at DESC").paginate(:page => params[:page],:per_page => 30)
  end

  def new
    @import = Import.new
    @import.uploader_user_id = current_user.id
  end

  def create
    @import = Import.new(import_params)
    @import.user = current_user
    @import.status = :ready
    @import.file_count = @import.dir_file_count
    if @import.save
      flash[:notice] = t('.flash')
      redirect_to import_url(@import)
    else
      flash[:error] = t('.error')
      render :action => 'new'
    end
  end


  def edit
  end

  def show
  end

  def destroy
    if @import.destroy
      flash[:notice] = t('.flash')
    else
      flash[:notice] = t('.error')
    end
    redirect_to imports_path
  end
 
  def update
    if @import.update_attributes(import_params)
      flash[:notice] = t('.flash')
      redirect_to import_url(@import)
    else
      flash[:error] = t('.error')
      render :action => 'edit'
    end
  end

  def start
    if @import.status == :ready
      @import.prepare_run
      Spawnling.new do
        @import.import!({:async => true})
      end
    end
  end

  def status
    #render :text => @import.status
    render :json => {:status => @import.status, :count => @import.imported_count}
  end

  def maps
    sort_init('created_at', {:default_order => "desc"})
    sort_update
    if params[:sort_order] && params[:sort_order] == "desc"
      sort_nulls = " NULLS LAST"
    else
      sort_nulls = " NULLS FIRST"
    end
    order_options = sort_clause + sort_nulls
    
    @maps = @import.maps.order(order_options).paginate(:page => params[:page],:per_page => 50)
  end
  
  def log
    send_file @import.log_path, :disposition => :inline, :type => 'text/plain'
  end
  
  def exports
    
  end

  private
  
  def find_import
    @import = Import.find(params[:id])
  end

  def check_imported
    if @import.status == :finished
      flash[:notice] = t('imports.start.already_imported_error')
      redirect_to imports_path
    end
  end

  def bad_record
    respond_to do | format |
      format.html do
        flash[:notice] = t('imports.show.not_found')
        redirect_to :root
      end
      format.json {render :json => {:stat => "not found", :items =>[]}.to_json, :status => 404}
    end
  end
  
  def import_params
      params.require(:import).permit(:name,:path, :map_title_suffix, :map_description, :map_publisher, :map_author, :layer_id, :layer_title,  :uploader_user_id, 
        :maps_attributes => [:title, :description, :publisher, :authors, :source_uri, :id, "_destroy"] )
  end

end

app/views/imports/_form.html.erb
<%= form_for @import do |f| %>
  <p>
    <b><%= f.label :name, "Name (give a name to the import, required)"  %></b> <br />
    <%= f.text_field :name %>
  </p>
  <p>
    <b><%= f.label :path, "Path on server for directory where maps are (required)"  %></b> <br />
    <%= f.text_field :path %>
  </p>
  <p>
    <b><%= f.label :map_title_suffix, "Map title suffix (added after filename, optional)"  %></b> <br />
    <%= f.text_field :map_title_suffix %>
  </p>
  <p>
    <b><%= f.label :map_description, "Default map description (optional)"  %></b> <br />
    <%= f.text_field :map_description %>
  </p>
  <p>
    <b><%= f.label :map_publisher, "Default map publisher (optional)"  %></b> <br />
    <%= f.text_field :map_publisher %>
  </p>
  <p>
    <b><%= f.label :map_author, "Default map authors (optional)"  %></b> <br />
    <%= f.text_field :map_author %>
  </p>
  <p>
    <b><%= f.label :layer_id, "Mosaic/Layer ID to add imported maps into existing mosaic/layer. -99 to create new layer, leave blank for no layer (optional)"  %></b> <br />
    <%= f.text_field :layer_id %>
  </p>
  <p>
    <b><%= f.label :layer_title, "Title for new mosaic/layer (if new layer required, see above)"  %></b> <br />
    <%= f.text_field :layer_title %>
  </p>
  <p>
    <b><%= f.label :uploader_user_id, "User id for user to be assigned as uploading these (defaults to you, required)"  %></b> <br />
    <%= f.text_field :uploader_user_id %>
  </p>

  <br />

  <%= f.submit((defined?(page) && page =~ /new/) ? "Create" : "Update" )%>
<% end  %>

app/views/imports/_import.html.erb
<tr class="<%= cycle('table0', 'table1') -%>">
  <td><%= link_to(import.id.to_s, import_path(import.id)) %> </td>
  <td><%= link_to(( h import.name), import_path(import.id), :method => :get)  -%></td>
  <td><%= link_to(pluralize(import.maps.count, t('common.map')), maps_import_path(import.id)) %> <%= t('.imported', :count => import.imported_count ) %></td>
  <td><%= link_to(( h import.user.login), user_path(import.user.id), :method => :get)  -%></td>
  <td><%=h time_ago_in_words(import.created_at) -%> ago</td>
  <td><%= import.state  %> </td>
  <td><% if admin_authorized? -%>
      <%  if import.state == "ready" -%>
        <%= link_to(t('.edit'), edit_import_path(import)) -%>
      <%  elsif import.state == "imported" -%>
        <%= link_to(t('.edit_maps'), maps_import_path(import)) -%>
      <% end  %>
    <%  end %> </td>
</tr>

app/views/imports/edit.html.erb
<h2><%= t('.header') %></h2>

<%= render :partial => "form" %>

app/views/imports/exports.html.erb
<h2><%= t('.header') %></h2>

<h3><%= t('.maps_csv_header') %></h3>
<%= link_to t('.maps_csv_file'), csv_maps_url %>

<h3><%= t('.gcps_csv_header') %></h3>
<%= link_to t('.gcps_csv_file'), csv_gcps_url %>

app/views/imports/index.html.erb
<h2><%= t('.header') %></h2>
<h3><%= link_to(t('.exports_link'), exports_url) %>  </h3>
<h3><%= t('.csv_header') %></h3>
<%= link_to t('.csv_link'), bulk_import_gcps_url%>
<hr />
<h3><%= t('.maps_header') %></h3>
<%= link_to t('.maps_link'), new_import_url %>
<%= will_paginate @imports %>
<table class="usertable">
  <thead>
    <tr>
      <th><%= t('.id') %></th>
      <th><%= t('.name') %></th>
      <th><%= t('.maps') %></th>
      <th><%= t('.user') %></th>
      <th><%= t('.created') %></th>
      <th><%= t('.status') %></th>
      <th><%= t('.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => "import", :collection => @imports %>
  </tbody>
</table>
<%= will_paginate @users %>

app/views/imports/maps.html.erb
<h2><%= t('.header', :name => @import.name ) %></h2>
<p>Created: <%= @import.created_at.to_s(:long) %> by <%= link_to(( h @import.user.login), user_path(@import.user.id), :method => :get)  -%></p>
<p>From: <%= @import.path %> Found <%= @import.file_count.to_s %> files in directory. Imported <%= @import.imported_count %> Maps.
</p>
<% if @layer %>
  <p>Mosaic: <%=link_to(@layer.name, layer_path(@layer))%></p>
<% else %>
  Maps not added to a Mosaic
<% end %>
<p>Assigned user to own the maps: <%= link_to(@upload_user.login, user_path(@upload_user)) -%></p>
<h3>Maps</h3>
<%= form_for @import do |import_form| %>
  <table>
    <% @import.maps.each do | map | %>
      <tr class="<%= cycle('table0', 'table1')%> import-maps " >
        <%= import_form.fields_for :maps, map do |map_form| %>
          <td>
            <%= image_tag(map.upload.url(:thumb)) %><br />
            <%=  link_to "View in Warper", map_path(map) %>
          </td>
          <td>
            <%= map_form.label "Filename" %> <span class="import-span-map"><%= map.upload_file_name %></span> <br />
            <%= map_form.label :title %>
            <%= map_form.text_field :title , { :class => 'import-textfield-map' } %><br />
            <%= map_form.label :description %>
            <%= map_form.text_area :description , { :class => 'import-textarea-map' } %><br />
            <%= map_form.label :publisher %>
            <%= map_form.text_field :publisher, { :class => 'import-textfield-map' }  %><br />
            <%= map_form.label :authors%>
            <%= map_form.text_field :authors , { :class => 'import-textfield-map' } %><br /><br />
            <%= map_form.label :source_uri%>
            <%= map_form.text_field :source_uri , { :class => 'import-textfield-map' } %><br /><br />

          </td>
          <td>

            <% unless map_form.object.new_record? %>
              <%= map_form.check_box '_destroy' %>
              <%= map_form.label '_destroy', 'Delete Map', { :class => 'import-delete-map' } %>
            <% end %>

          </td>
        </tr>
      <% end %>
    <% end  %>
  </table>
  <%= submit_tag %>
<% end %>

app/views/imports/new.html.erb
<h2><%= t('.header') %></h2>

<%= render :partial => "form", :locals => {:page => "new"} %>

app/views/imports/show.html.erb
<%= link_to "&lt; Browse imports".html_safe, imports_path %>

<h2>Import: <%=h @import.name %></h2>
<p>Created: <%= @import.created_at.to_s(:long) %> by <%= link_to(( h @import.user.login), user_path(@import.user.id), :method => :get)  -%></p>
<p>Status: <b><%= @import.state %> </b></p>
<p><b>Path</b><br />
  <%= @import.path %>
</p>
<p><b>Map title suffix - added before filename </b><br />
  <%= @import.map_title_suffix  %>
</p>
<p><b>Default map description</b> <br />
  <%= @import.map_description %>
</p>
<p><b>Default map publisher</b> <br />
  <%= @import.map_publisher %>
</p>
<p><b>Default map authors </b><br />
  <%= @import.map_author %>
</p>
<p><b>Layer/Mosaic ID to add imported maps into existing layer. -99 to create new layer, blank for no layer </b><br />
  <%= @import.layer_id %>
</p>
<p><b>Layer/Mosaic title if one needs to be created</b><br />
  <%= @import.layer_title %>
</p>
<p><b>Assigned user to own these</b><br />
  <%= @import.uploader_user_id %>
</p>

<br />
<% if admin_authorized? %>
  <%=link_to('Edit this import', edit_import_path(@import)) %><br /><br />
  <%=  link_to 'Delete this import. (Does not delete maps)', {:controller=>"imports", :action =>"destroy", :id => @import},  :method => :delete, :data => {:confirm => "Are you sure?"} %>
  <br /> <br />
  <% if @import.state =="ready" %>
    <b><%=link_to('START IMPORT', start_import_path(@import), :data => {:confirm => "Ready to Start this import?"} ) %></b>
  <% else %>
    <%=link_to('Edit Maps', maps_import_path(@import)) %>
  <% end %>
<%end%>

app/views/imports/start.html.erb
<script type="text/javascript">
  var keepOnPolling = true;
  function pollServer() {
    if (keepOnPolling) {
      jQuery.ajax({
        method: 'get',
        url: '<%= status_import_path(@import)%>',
        dataType: 'text',
        success: function(text) {
          console.log(text);
          if (text.indexOf("Finished") != -1) {
            keepOnPolling = false;
            jQuery('#afterImport').show();
            jQuery('#spinner').hide();
          }
          jQuery('#updateMe').html(text);
        },
        error: function() {
          keepOnPolling = false;
          jQuery('#updateMe').html("<%= t('.error') %>");
          jQuery('#spinner').hide();
        }
      });
    } else {
      jQuery('#spinner').hide();
    }
  }




  jQuery(document).ready(function() {
    jQuery('#afterImport').hide();
    jQuery('#spinner').show();
    var myvar = setInterval(pollServer, 4000);

  });

</script>

<h2><%= t('.header') %></h2>

<span id="spinner" style="display:none;"><%= image_tag 'spinner-horiz.gif' %></span>
<%= t('.progress') %><br />
<div id="updateMe">
  <%= t('.importing') %>
</div>
<div id="afterImport">
  <h3><%= t('.finished_notice') %></h3>
  <%= link_to t('.edit_maps_link'), maps_import_path(@import) %>
</div>